services:
  # ===============================
  # 1. POSTGRESQL VERİTABANI (Sadece Engine İçin)
  # ===============================
  postgres:
    image: postgres:15-alpine
    container_name: matching-postgres
    restart: always
    environment:
      POSTGRES_DB: matching_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      PGPORT: 5437
    ports:
      - "5437:5437"
    volumes:
      - matching-pgdata:/var/lib/postgresql/data

  # ===============================
  # 2. REDIS (IN-MEMORY VERİ)
  # ===============================
  redis:
    image: redis:7-alpine
    container_name: matching-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - matching-redisdata:/data

  # ===============================
  # 3. JAVA EŞLEŞTİRME MOTORU
  # ===============================
  java-engine:
    build: .
    container_name: matching-java-engine
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      # Spring Boot'u Profil Seçimi
      - SPRING_PROFILES_ACTIVE=virtual
      
      # application.properties içindeki localhost ayarlarını eziyoruz
      - SPRING_DATASOURCE_URL=jdbc:postgresql://matching-postgres:5437/matching_db
      - SPRING_DATA_REDIS_HOST=matching-redis

# Verilerin WalkTogether ile karışmaması için Volume isimleri özelleştirildi
volumes:
  matching-pgdata:
  matching-redisdata: