spring.application.name=core-engine
 
# Testi hangi mimariyle yapmak istiyorsan buraya onu yaz (virtual veya classic)
spring.profiles.active=virtual

# 1: Tomcat'in 200 klasik thread limitini kaldirir, milyonlarca Virtual Thread kullanmasini saglar!
spring.threads.virtual.enabled=true

server.port=8080

# Veritabani ayarlari
spring.datasource.url=jdbc:postgresql://localhost:5437/matching_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

# sql loglarini kapatik
spring.jpa.show-sql=false

# sql baglantilarinin webde kalmasini engeller
spring.jpa.open-in-view=false

# database'e teker teker yazmak yerine 50'ser 50'ser yazar.
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Redis Ayarlari
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Redis Optimizasyonlari
spring.data.redis.lettuce.pool.max-active=200
spring.data.redis.lettuce.pool.max-idle=100
spring.data.redis.lettuce.pool.min-idle=20


# HikariCP Optimizasyonlari
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=20000

# --- TOMCAT WEB SUNUCUSU Optimizasyonlari
server.tomcat.max-connections=20000
server.tomcat.accept-count=2000